apiVersion: v1
kind: Service
metadata:
  name: nlp-summarizer-service
spec:
  type: NodePort  # Use NodePort for local testing instead of LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      nodePort: 30001  # This can be any free port between 30000-32767
  selector:
    app: nlp-summarizer
