name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
        sudo installer -pkg AWSCLIV2.pkg -target /

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        zip -r application.zip .
        aws s3 cp application.zip s3://textsummarizer-deploy-bucket/
        aws elasticbeanstalk create-application-version \
            --application-name nlptextsummarizer \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket="textsummarizer-deploy-bucket",S3Key="application.zip"
        aws elasticbeanstalk update-environment \
            --environment-name Nlptextsummarizer-env \
            --version-label ${{ github.sha }}
