name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Or the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive application
      run: zip -r app.zip . -x "venv/*"

    - name: Upload to S3
      run: |
        aws s3 cp app.zip s3://textsummarizer-deploy-bucket/app.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-southeast-2  # Use the region where your S3 bucket is located

    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version --application-name textsummarizer --version-label ${{ github.sha }} --source-bundle S3Bucket="textsummarizer-deploy-bucket",S3Key="app.zip"
        aws elasticbeanstalk update-environment --application-name textsummarizer --environment-name textsummarizer-env --version-label ${{ github.sha }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-southeast-2  # Use the region where your Elastic Beanstalk environment is located
